import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // A self-contained server.js plus only the node_modules it needs, for
  // V-Gruvs (our DigitalOcean host) and the Dockerfile. Vercel ignores it.
  output: 'standalone',
  experimental: {
    optimizePackageImports: ['lucide-react', 'framer-motion'],
    // Keep pages regenerated by ISR in memory instead of writing them into
    // .next/server/app. On V-Gruvs the release folder is read-only to the
    // app (it cannot change its own code), so those writes would fail on
    // every revalidation. Vercel's builds force this to false as well.
    isrFlushToDisk: false,
  },
  // Pinned because an empty, orphaned package-lock.json sits in the user's
  // home directory (no package.json, no node_modules beside it — junk from a
  // stray `npm install` run there once). Next walked up, found it, and
  // inferred the wrong workspace root on every single build. Pinning here
  // rather than deleting a file outside the repo: this fix is version
  // controlled and survives on any machine.
  turbopack: {
    root: __dirname,
  },
  // Same reason, for the standalone trace: without it, server.js lands at
  // .next/standalone/<path from the stray lockfile's folder>/server.js.
  outputFileTracingRoot: __dirname,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: '*.supabase.co',
      },
      {
        protocol: 'https',
        hostname: 'cdnjs.cloudflare.com',
      }
    ],
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on'
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload'
          },
          // These two used to disagree with src/proxy.ts, which sets DENY and
          // strict-origin-when-cross-origin on /dashboard and /api. Two
          // sources of truth for security headers that contradict each other
          // is how a policy silently ends up weaker than anyone intended, so
          // both now state the stricter value. DENY is consistent with the
          // CSP's `frame-ancestors 'none'`, and nothing in this app is meant
          // to be embedded anywhere.
          {
            key: 'X-Frame-Options',
            value: 'DENY'
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin'
          }
        ]
      }
    ]
  }
};

export default nextConfig;
