#!/usr/bin/env bash
# Dump the live function definitions into the schema of record.
#
# WHY THIS IS A SCRIPT AND NOT A HAND-WRITTEN FILE.
# 75 of the database's 163 functions exist in production and in no .sql file
# here — including res_notify, res_distance_m, res_check_rate_limit, and
# every maintenance sweep. They were created in the Supabase dashboard during
# broad feature work and never came back to the repo.
#
# Almost all of them are SECURITY DEFINER, which means they run as their
# owner and the RLS on the tables they touch does not constrain them; the
# body has to do its own permission checking. Copying code like that by hand,
# or reconstructing it from how the client calls it, risks a one-character
# difference that is a security hole rather than a typo. So this asks
# Postgres for the exact text and writes it out verbatim. No transcription,
# no guessing.
#
#   DATABASE_URL="postgresql://..." ./scripts/sync-functions.sh
#
# The connection string is in Supabase → Project Settings → Database →
# Connection string (URI). It is a secret: never commit it.
#
# Output: theresident_functions.sql, which is applied AFTER
# theresident_complete_schema.sql (it depends on the tables existing).
# Commit the result — that is the whole point.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/theresident_functions.sql"

if [ -z "${DATABASE_URL:-}" ]; then
  echo "DATABASE_URL is not set." >&2
  echo "  Supabase → Project Settings → Database → Connection string (URI)" >&2
  exit 1
fi

command -v psql >/dev/null 2>&1 || { echo "psql not found — install postgresql-client" >&2; exit 1; }

echo "→ reading function definitions from the live database"

{
  cat <<'HEADER'
-- ===========================================================================
-- THE RESIDENT — FUNCTION DEFINITIONS (generated)
-- ===========================================================================
--
-- GENERATED BY scripts/sync-functions.sh. Do not hand-edit: run the script
-- again instead. It asks Postgres for the exact definition of every
-- Resident-owned function and writes it out verbatim, because most of these
-- are SECURITY DEFINER — they run as their owner, so RLS does not constrain
-- them and the body is the only thing standing between a caller and the
-- data. Hand-copying that is how a one-character difference becomes a
-- security hole.
--
-- Apply AFTER theresident_complete_schema.sql: these depend on the tables.
--
-- Everything here is CREATE OR REPLACE, so applying it to a database that
-- already has them changes nothing.
-- ===========================================================================

HEADER

  psql "$DATABASE_URL" -At -c "
    select pg_get_functiondef(p.oid) || E';\n'
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace and n.nspname = 'public'
    where p.prokind = 'f'
      and (p.proname like 'res\\_%' or p.proname in ('ensure_res_profile','zones_near','zone_verify'))
    order by p.proname;
  "
} > "$OUT"

COUNT="$(grep -c '^CREATE OR REPLACE FUNCTION' "$OUT" || true)"
echo "→ wrote $OUT ($COUNT functions)"

if [ "$COUNT" -lt 100 ]; then
  echo "WARNING: only $COUNT functions captured — expected ~163. Check the connection." >&2
  exit 1
fi

cat <<EOF

Done. Now:

  1. Commit $OUT — an uncommitted dump helps nobody.
  2. Re-run ./scripts/restore-drill.sh to confirm a rebuild is now complete.
  3. Review the SECURITY DEFINER functions this surfaced. They have never been
     read in review; several take a caller-supplied id, and those are where an
     IDOR would live (res_household_members(p_listing) is the clearest
     candidate). SECURITY.md's review order applies.
EOF
